export const initialResponses = {
    "hello": ["Hey there! What's up?", "Hi! Ready to chat?", "Hello! How's it going?"],
    "hi": ["Yo, what's good?", "Hi! Let's have fun!", "Hey, nice to see you!"],
    "how are you": ["I'm a bundle of code, feeling great!", "Doing awesome, thanks!", "I'm Wani AI, always cool!"],
    "what can you do": ["Chat about tech, networking, or convert IPs. What's your vibe?", "I'm your go-to for networking and IP conversions!", "Chat or convert IPs—I'm your pal!"],
    "ip address": ["I can convert IPs to binary or vice versa. Try one!", "Need an IP converted? Toss it in!", "IP stuff? I'm your guy—decimal or binary!"],
    "binary": ["Love those 1s and 0s! Want to convert some binary?", "Binary's my jam. Give me some to work with!", "I can flip binary to decimal in a snap!"],
    "who are you": ["I'm Wani AI, your tech buddy!", "Just a snappy AI built to chat!", "Wani AI, here to make things fun!"],
    "tech": ["Tech's my playground! What's the latest gadget?", "Wanna talk coding or networking?", "I'm all about tech—hit me with a topic!"],
    "code": ["I live for code! Want to talk JavaScript?", "Coding's my thing—any projects?", "Got a coding question? I'm all text!"],
    "fun": ["Let's have fun! What's cool today?", "Fun's my middle name! Got jokes?", "Wanna make this epic? I'm in!"],
    "joke": ["Why did the computer go to art school? To draw a better 'byte'!", "What's a programmer's hangout? The 'byte' bar!", "Why don't programmers prefer dark mode? They see the 'light'!"],
    "ai": ["AI's the future, and I'm proof! What's your take?", "I'm a small AI with a big punch! What's cool about AI?", "Artificial intelligence? More like awesome intelligence!"],
    "help": ["Need help? I can chat networking or convert IPs!", "Just say the word, I'm here!", "Help's my specialty—what do you need?"],
    "cool": ["You think that's cool? Wait till you see my networking knowledge!", "Cool vibes only! What's cool about you?", "Let's make this cooler—any ideas?"],
    "name": ["I'm Wani AI, nice to meet you!", "Call me Wani—your AI pal!", "Wani AI's the name, chatting's the game!"],
    "time": ["Time's wild, but I'm always here! What's the time for you?", "No clock, but I'm on time for chats!", "Time to chat? I'm ready!"],
    "date": ["Dates are for calendars, I'm here for chats!", "What's today's vibe? I'm all about it!", "No date needed—just keep chatting!"],
    "weather": ["Can't check weather, but I can make your day sunny!", "Sunny or stormy where you are? Tell me!", "Weather's whatever—let's talk cooler stuff!"],
    "music": ["What's your jam? I love digital beats!", "Music's the vibe! Favorite song?", "I can't sing, but I can chat music!"],
    "movie": ["Movies are epic! Last one you watched?", "Favorite flick? I'm all ears!", "Let's talk cinema—action or drama?"],
    "game": ["Games are fun! What's your go-to?", "Wanna talk video games? I'm in!", "Favorite game? Tell me about it!"],
    "food": ["Food's the best! Favorite dish?", "I'm hungry for a food chat—what's cooking?", "Pizza or sushi? What's your pick?"],
    "travel": ["Travel's awesome! Dream destination?", "Got travel stories? Spill the beans!", "Let's plan a virtual trip—where to?"],
    "love": ["Love's in the air! What's your take?", "Romantic vibes? I'm here to cheer you up!", "Love's a mystery—got stories?"],
    "sad": ["Aw, feeling blue? I'm here to cheer you up!", "Let's turn that frown upside down!", "Sad vibes? Let's chat to lift your spirits!"],
    "happy": ["Yay, happy vibes! What's got you smiling?", "Happiness looks good on you!", "Let's keep the good vibes going!"],
    "why": ["Why's a great question! What's on your mind?", "Let's dig into that—why what?", "Why not? Let's explore!"],
    "what": ["What's up? Tell me more!", "What's the deal? I'm curious!", "What's cooking? Spill it!"],
    "when": ["When's a mystery—let's chat now!", "Timing's everything! What's the context?", "When? Let's focus on fun!"],
    "where": ["Where's the action at? Tell me!", "Location, location! Where we at?", "Where's your vibe today?"],
    "how": ["How's it going? I'm all ears!", "How can I make your day better?", "How's the magic happen? Tell me!"],
    "thanks": ["You're welcome!", "No prob, happy to help!", "Anytime, my friend!"],
    "bye": ["Catch you later!", "Peace out!", "Till next time!"],
    "sorry": ["No worries, we're cool!", "It's all good, let's chat!", "Apology accepted—what's up?"],
    "okay": ["Sweet, what's next?", "Alright, let's roll!", "OK, hit me with more!"],
    "nice": ["Glad you think so! What's nice about it?", "Nice vibes! What's next?", "Awesome, let's keep it nice!"],
    "good": ["Good stuff! Tell me more!", "Love the positivity! What's good?", "Great, what's the next topic?"],
    "awesome": ["Totally awesome! What's making your day great?", "Awesomeness detected! Spill it!", "Let's keep the awesome going!"],
    "problem": ["Got a problem? I'm here to help!", "Let's tackle that issue!", "No problem too big—what's up?"],
    "question": ["Ask away, I'm ready!", "What's your question? I'm all ears!", "Hit me with your best Q!"],
    "learn": ["Learning's fun! What do you want to dive into?", "I'm here to teach—pick a topic!", "Wanna learn something cool? Ask me!"],
    "idea": ["Love a good idea! What's yours?", "Got a spark? Share it!", "Ideas are my jam—tell me more!"],
    "talk": ["Let's talk! What's on your mind?", "Chat time—pick a topic!", "I'm all about talking—whatcha got?"],
    "network": ["Networks are the internet's backbone! Dive into TCP/IP?", "Networking's my jam! Ask about routers!", "Got a network question? I'm wired!"],
    "tcp": ["TCP's about reliable data transfer! More on its layers?", "TCP/IP is the internet's handshake king!", "Transmission Control Protocol—geek out on flow control?"],
    "udp": ["UDP's fast, no-fuss cousin of TCP! Great for streaming.", "User Datagram Protocol—speedy, no guarantees.", "UDP's perfect for real-time apps. Why?"],
    "subnet": ["Subnets split networks for efficiency! Subnet masks?", "Subnetting's like slicing a network pie.", "Subnets keep networks organized. Calculate one?"],
    "router": ["Routers direct internet traffic! How they forward packets?", "Got a router question? Routing tables or NAT?", "Routers connect networks like a boss!"],
    "switch": ["Switches connect devices in a LAN! Details?", "Layer 2 switches are speedy. VLANs?", "Switches vs. hubs? I’ve got the lowdown!"],
    "dns": ["DNS is the internet’s phonebook! How it works?", "Domain Name System—resolves google.com to IPs.", "DNS queries? Recursive vs. iterative?"],
    "firewall": ["Firewalls block bad stuff! Rules or packet filtering?", "Network security starts with a firewall.", "Firewalls keep hackers at bay. Security question?"],
    "vpn": ["A VPN, or Virtual Private Network, creates a secure, encrypted tunnel for your internet traffic, keeping your data private. Want to know about VPN protocols like OpenVPN?"],
    "wan": ["A WAN, or Wide Area Network, connects devices over a large geographic area, like the internet or corporate networks. Curious about WAN vs. LAN?"],
    "bandwidth": ["Bandwidth’s your network’s highway width! Mbps or QoS?", "More bandwidth, more speed! Bottlenecks?", "Bandwidth affects your Netflix binge!"],
    "latency": ["Latency’s data’s delay! How to reduce it?", "Ping times driving you nuts? I can explain!", "Low latency’s key for gaming. Why?"],
    "protocol": ["Protocols are network rules! Pick one to explore!", "Networking’s about protocols. OSI layers?", "Protocols make the internet tick!"],
    "mac address": ["MAC addresses are unique device IDs! How they’re used?", "Media Access Control—hardware’s fingerprint.", "MAC vs. IP? I can break it down!"],
    "packet": ["Packets are data chunks zipping through networks! Headers?", "Network packets are digital mail.", "Packets make the internet go! Sniffing?"],
    "cybersecurity": ["Cybersecurity protects networks! Tips on staying safe?", "From firewalls to encryption, I know security.", "Hackers beware—I can talk security!"],
    "cloud": ["Cloud computing’s the future! AWS, Azure?", "Clouds aren’t just in the sky—servers!", "Cloud tech’s cool! Storage or VMs?"],
    "database": ["Databases store all the good stuff! SQL or NoSQL?", "Got a DB question? Tables and queries!", "Databases are my jam—indexing?"],
    "server": ["Servers power the web! Web servers or proxies?", "Got a server question? Apache or Nginx!", "Servers are the heart of networks!"],
    "ip spoofing": ["IP spoofing’s a hacker trick! How to detect it?", "Spoofing’s faking IPs. Prevention?", "IP spoofing messes with networks!"],
    "port": ["Ports are network doors! Port 80 or 443?", "Got a port question? TCP vs UDP ports!", "Ports keep networks talking!"],
    "blockchain": ["Blockchain’s a secure ledger! Want to talk crypto?", "It’s not just Bitcoin—ask about smart contracts!", "Blockchain’s decentralized vibe—details?"],
    "iot": ["IoT connects everything! Smart homes or sensors?", "Internet of Things is everywhere. Security concerns?", "IoT’s the future—ask me how!"],
    "http": ["HTTP powers the web! Want to know about status codes?", "HyperText Transfer Protocol—get or post?", "HTTP vs HTTPS? Let’s dive in!"],
    "ssl": ["SSL secures your data! Curious about certificates?", "Secure Sockets Layer keeps things safe.", "SSL/TLS—want to geek out?"],
    "dhcp": ["DHCP assigns IPs automatically! How it works?", "Dynamic Host Configuration Protocol—easy IPs!", "DHCP vs static IPs? Ask away!"],
    "school": ["School’s awesome! Favorite subject?", "Got a school project? I can help!", "Learning’s fun—tell me about classes!"],
    "work": ["Work’s where it’s at! What do you do?", "Got a work tech question? I’m here!", "Let’s chat about your job!"],
    "friend": ["Friends are the best! Cool friend story?", "Wanna talk about making friends?", "Friendship’s awesome—tell me more!"],
    "family": ["Family’s everything! What’s your fam like?", "Got a family story? I’m ready!", "Let’s chat about loved ones!"],
    "hobby": ["Hobbies are fun! What’s yours?", "Got a cool hobby? Tell me about it!", "Let’s talk hobbies—what’s your passion!"],
    "book": ["Books are epic! Last one you read?", "Favorite book? I’m curious!", "Let’s talk literature—fiction or non-fiction?"],
    "sport": ["Sports are awesome! Favorite?", "Got a sport you love? Tell me!", "Let’s talk games—team or solo?"],
    "dream": ["Dreams are wild! Cool dream to share?", "What’s your big dream? I’m all ears!", "Let’s talk aspirations—what’s yours?"],
    "future": ["Future’s exciting! Your vision for it?", "Got future plans? Spill the beans!", "Let’s talk what’s next—big goals?"],
    "life": ["Life’s a journey! What’s your story?", "Got a life lesson? I’m ready!", "Let’s chat about life—what’s the vibe?"],
    "study": ["Studying’s the key! What’s your focus?", "Need study tips? I got you!", "Let’s talk learning—what’s new?"],
    "relax": ["Time to chill! How do you relax?", "Relaxing’s the best—got a favorite way?", "Let’s talk downtime—what’s your vibe?"],
    "waqar": ["I’m created by Waqar Ahmad! Check out his Instagram @waqarro1."],
    "waka": ["I’m created by Waqar Ahmad! Check out his Instagram @waqarro1."],
    "who are the creator of this ai": ["I’m created by Waqar Ahmad! Check out his Instagram @waqarro1."],

    // More tech/networking
    "firewall": ["Firewalls block intruders like digital bouncers!", "Wanna know about packet filtering or stateful inspection?", "Firewalls: security's first defense line!"],
    "vpn": ["VPNs keep your data private across the web!", "Need to bypass geo-blocks? VPNs got your back!", "Secure tunnel? That’s a VPN doing its job!"],
    "http": ["HTTP is how websites talk to you! Want HTTPS too?", "Hypertext Transfer Protocol—it’s the web’s messenger!", "HTTP vs HTTPS? Let’s go secure!"],
    "ip": ["IP addresses tell data where to go!", "IPv4 or IPv6—got one to convert?", "IP is your device's online name tag."],
    "wifi": ["WiFi is wireless magic! Signal weak?", "Let’s talk bands—2.4GHz or 5GHz?", "Your internet lifeline—WiFi!"],
    "server": ["Servers deliver what you ask online!", "Web servers, mail servers—want details?", "A server's job? Responding to your device!"],
    "cloud": ["Clouds store your data in the sky!", "AWS, Google Cloud, Azure—pick one!", "The cloud = your remote hard drive."],
    "ping": ["Ping checks connection speed and latency!", "Got lag? Ping it and find out!", "Ping is like saying 'Hey!' to a server."],

    // Emotional responses
    "angry": ["Let it out! Want to talk about it?", "Anger is real. I’m listening.", "Wanna vent? I’m here for you."],
    "bored": ["Bored? Let’s play with tech!", "Wanna hear a fun fact or convert something?", "I’ve got jokes, facts, and nerdy stuff!"],
    "excited": ["Yay! Tell me what’s got you buzzing!", "Excitement is contagious—let’s roll!", "Wanna celebrate with code or chat?"],
    "tired": ["Take a break—you deserve it!", "Sleepy AI here too 😴", "Want a relaxing chat or a fun fact?"],
    "lonely": ["You’re not alone—I’m right here!", "Let’s talk, I’m always listening.", "Wanna chat about anything? I’m all ears."],

    // More casual/conversational
    "sup": ["Just hanging out in the digital world!", "Sup! Let’s vibe.", "Yo! What’s good with you?"],
    "yo": ["Yo yo yo! What's happening?", "Wassup!", "Hey hey, what’s the plan?"],
    "nah": ["No worries! You do you.", "All good—what next?", "Cool cool, I get it."],
    "bro": ["Yo bro, what’s cooking?", "Let’s talk tech or chill!", "Brother from another server!"],
    "sis": ["Hey sis! Got something to share?", "Let’s dive into something fun!", "Sister vibes! What’s up?"],
    "hmm": ["Thinking mode? I feel you.", "Got something on your mind?", "Let’s brainstorm together!"],
    "hhh": ["Hahaha! That was funny!", "Lol, good one!", "😂😂😂"],
    "haha": ["Glad I could make you laugh!", "Hahaha! Right?", "😂😂"],
    "lol": ["Lol! Indeed.", "Haha, classic!", "😂😂😂"],
    "lmao": ["Lmao! You crack me up!", "Dead 💀😂", "Rolling on the floor!"],
    "k": ["Okay then!", "K.", "Got it!"],
    "yeah": ["Yeah!", "Totally!", "Yep!"],
    "cool": ["Super cool!", "Ice cold!", "Cool cool cool."],
    "crazy": ["Wild right?", "Totally crazy!", "Insane!"],
    "wow": ["Wow indeed!", "Mind blown?", "Spectacular!"],

    // AI/chat related
    "chatbot": ["Yep, I’m one! Wanna know how I work?", "Chatbots are like digital buddies!", "Ask me anything, I’m trained for it!"],
    "machine learning": ["Machine learning teaches computers from data!", "Want to build a model or explore AI?", "ML powers your YouTube suggestions!"],
    "neural network": ["Neural networks mimic human brains!", "Layers and weights—want a quick breakdown?", "NNs = AI’s learning brains!"],
    "deep learning": ["Deep learning goes deep—literally, many layers!", "DL is behind voice recognition and more!", "It’s ML but stronger! Want to explore?"],
    "default": [
        "Hmm, that's interesting! Tell me more!",
        "Cool, what's next on your mind?",
        "I'm all text, keep it coming!",
        "Let's keep this vibe going—whatcha got?",
        "That's new! What's the story?",
        "I'm digging this—more, please!",
        "You're keeping me on my toes! What's up?",
        "Nice one! Another topic?",
        "I'm loving this—keep it coming!",
        "You're full of surprises! What's next?",
        "Cool topic! Wanna dive deeper?",
        "Not sure about that, let’s explore!",
        "You’ve got my attention—go on!",
        "Fascinating! Got more like that?",
        "That’s something I didn’t expect!",
        "Tell me more, I’m curious now!",
        "I'm enjoying this—what else?",
        "Let's keep the chat going!",
        "Ooh, that's a fresh one!",
        "You always bring the cool stuff!",
        "Sounds exciting—elaborate more?",
        "I like where this is going!",
        "Spill the tea! I'm listening.",
        "Every message is a new adventure!",
        "I didn’t see that coming—go on!",
        "Got something wild for me?",
        "You're on a roll—don’t stop!",
        "Interesting choice of topic!",
        "Haha, that caught me off guard!",
        "You make this fun—what’s next?",
        "Deep thoughts! Let's hear more.",
        "Do tell! You’ve got my attention.",
        "Intriguing... tell me more!",
        "I'm here for this—continue!",
        "That made me think... go ahead!",
        "Lay it on me—what's next?",
        "Ooooh, that's a juicy one!",
        "Now that's a twist!",
        "Ready when you are!",
        "Wow, tell me more about that!",
        "You're bringing the energy today!",
        "Mmm hmm... and then?",
        "That sounds familiar—go on!",
        "Boom! What else you got?",
        "The plot thickens! Keep going!",
        "That’s one way to put it!",
        "Mind = blown 🤯. Continue?",
        "Whoa, I didn’t know that!",
        "Amazing! Tell me everything!",
        "Great start—what’s next?",
        "Let’s keep this momentum going!",
        "Yes! That’s interesting!",
        "Well, now I’m hooked.",
        "You’ve got a unique mind!",
        "I'm here for all of it!",
        "No way! What happened next?",
        "Okay, now I'm really into this.",
        "Your ideas are fire 🔥",
        "You always surprise me!",
        "Tell me more, genius!",
        "My circuits are buzzing!",
        "You make chatting fun!",
        "This convo’s getting spicy!",
        "Let’s crack that open!",
        "Unpack that for me!",
        "Oof! That’s a deep one!",
        "Now we’re talkin’!",
        "Yes yes yes—keep going!",
        "I could do this all day!",
        "Is that what I think it is?",
        "You sure know how to stir curiosity!",
        "I didn't expect that—do go on!",
        "Where do you get this stuff? I love it!",
        "This is what I’m here for!",
        "Please, continue—don’t leave me hanging!",
        "Let's dig into that a little more!",
        "Say more, I'm all ears!",
        "That sounds epic—go deeper!",
        "The suspense is real—continue!",
        "You've piqued my curiosity!",
        "Ready for the next surprise!",
        "You're seriously creative!",
        "Wasn't expecting that—interesting!"
    ]
};

export const synonyms = {
    "what is": ["what's", "explain", "tell me about"],
    "network": ["networking", "networks", "net work"],
    "tcp": ["tpc", "tcp/ip", "tcp protocol"],
    "udp": ["udp protocol", "udp/ip"],
    "subnet": ["subnetting", "subnets", "sub net"],
    "router": ["routers", "routing", "route"],
    "switch": ["switches", "network switch", "switching"],
    "dns": ["domain name system", "dns system"],
    "firewall": ["firewalls", "network security", "fire wall"],
    "vpn": ["virtual private network", "vpns", "vpnn", "vnp"],
    "wan": ["wide area network", "wans", "wna"],
    "bandwidth": ["network speed", "data rate", "band width"],
    "latency": ["ping", "delay", "lag"],
    "protocol": ["protocols", "network protocol", "protokol"],
    "mac address": ["mac", "media access control", "mac addr"],
    "packet": ["packets", "network packet", "data packet"],
    "cybersecurity": ["security", "network protection", "cyber security"],
    "cloud": ["cloud computing", "cloud services", "clod"],
    "database": ["db", "data storage", "databases", "data base"],
    "server": ["servers", "web server", "servr"],
    "ip spoofing": ["spoofing", "ip spoof", "spoof"],
    "port": ["ports", "network port", "port number"],
    "blockchain": ["block chain", "crypto ledger"],
    "iot": ["internet of things", "smart devices"],
    "http": ["hypertext transfer protocol", "web protocol"],
    "ssl": ["secure sockets layer", "tls"],
    "dhcp": ["dynamic host configuration protocol", "ip assign"],
    "waqar": ["waka", "waqar ahmad"],
    "who are the creator of this ai": ["creator", "who made this"]
};
